In [1]:
def calc_mode(num):
    mode = 0
    if len(set(num)) == 1:
        mode = num[0]
    else:
        mode = max(set(num), key=num.count)
    return mode

lst = [3, 4, 5, 4, 3, 4, 2, 3]
mode = calc_mode(lst)
print("Mode :", mode)

Mode : 3


In [66]:
# Numpy

import numpy as np

lst1 = [list(range(1, 11))]
print(lst1)

lst2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
arr2 = np.array(lst2)
print(arr2)

lst = [[1, 2], [3, 4], [5, 6]] # increasing the brackets will increases the dimensions of the array

arr = np.array(lst)

arr

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
arr.shape

(3, 2)